### PR TITLE
Development- Final Push for the 2014 Apple Website

### PR DESCRIPTION
**Pull request by shubham14p3**
- I have completed cloning the Apple Website.
- I used Normalised  CSS to normalise the behaviour of screen for multiple devices. I have use background images, practiced their positioning. 
- I also used Stylelint and W3CHTML validator to make sure there are no huge mistakes.

### CODE REVIEW

**Comment by davitomix** [comment]
Pull Request under review by David Elí 👨‍💻

**Comment by davidmrtz-dev** [comment]
### **Status: Changes required.** 🔍 ♻️ 
****
### Hi @shubham14p3 . 😄 
### Very good job so far.
### However, the following issues need to be fixed before moving on  👨‍💻  ⬇️ 

****

- [ ] Navbar.

Your navbar looks great! but we have to do a couple of changes to make it look as similar as possible to the page on which the project is based.
Please style your "ul" and remove the blank space between the "li" elements.
Use gradients to achieve the "brightness effect" on each element on the navbar.

How it looks now. ⬇️ 

Screen Shot 2020-03-10 at 7 17 29 PM

The example on which the project is based. ⬇️ 

Screen Shot 2020-03-10 at 7 17 39 PM


****

- [ ] Commits.

Make more descriptive commits.

Screen Shot 2020-03-10 at 7 20 10 PM

You can follow this [guideline](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). 😄 

****
### Optional.

- [ ] Background image.

You can align your navbar to look like the original page.

How it looks now. ⬇️ 

Screen Shot 2020-03-10 at 7 24 42 PM


The example on which the project is based. ⬇️ 

Screen Shot 2020-03-10 at 7 24 46 PM


****

### **Please kindly make the changes required and submit a new code review once you are ready!** 🙏 

Happy coding! 😄 💻  
If you have any questions or need help, you can message me on slack (@ David Eli Martinez Garcia).

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Comment by shubham14p3** [comment]
- Navbar Fixed
- Navbar alignment with Background Fixed
- The Description for name "Patch" was mentioned as No descriptive name were there since it was Syntax changes & pushing the same thing over & over with same name is wrong practice, So I Gave the name as Patch which is a good practice as well as per my knowledge.

Kindly check the updated Codes fr the changes you asked.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @shubham14p3 
### Well done :clap: However, you have an issue to make before your project could be approved.
- In the navigation, you are expected to use background and gradient, instead, you have only used background. Add gradient
nav
### Implement the issue and resubmit for another code review. Good luck.
- Happy coding!

**Comment by shubham14p3** [comment]
Update 
- Changed Background Image to Gradient
- Updated Screenshot

**Review by rOluochKe — APPROVED** [review]
Hello @shubham14p3 
### Good job done and for also implementing changes from the previous reviews :clap: I, therefore, approve of this project. Congratulations :boom: :100:
### You can merge and submit a project completion form from your dashboard. Good luck with the next project. 
- Happy coding!

**Pull request merged**
